### ISSUE TITLE
[Feature Request]: Schedule user onboarding / offboarding

### ISSUE THREAD

**Issue by CDSFounder** [BNWEIN/CIPPAPIModule#17]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi, 

Firstly, LOVE your PowerShell module. We are using it for some automation at our MSP! 😁

Was discussing scheduled tasks today in the CIPP Office Hours and noticed that the PowerShell module does not have support for Scheduled Tasks. 

We would like to be able to schedule a user offboarding (or onboarding) for a specific day and time. We would also want to utilize the callback feature and the additional properties feature (so that we can store our ticket number to reference it later).

Is this something on the radar for the near term? 😊

**Comment by BNWEIN** [comment]
Just a place holder reply for now. I’m away until September enjoying some family time and lots of sangria on the beach! Happy to look at adding this on my return or of course you are welcome to create a PR (to dev) and add it your self!

**Comment by CDSFounder** [comment]
Enjoy your time off! 😊

**Comment by BNWEIN** [comment]
@kris6673 has kindly added this to dev. I will push to main later today. Closing this off @CDSFounder
