### ISSUE TITLE
[Feature Request]: OneDrive Usage Report

### ISSUE THREAD

**Issue by PatyYe** [BNWEIN/CIPPAPIModule#18]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi, 

It would be nice if you could add the CIPP API for OneDrive.
You need to call in the same API for Sharepoint list. Suggested code should return the correct info. Using your code from Sharepoint.

### PowerShell commands you would normally use to achieve above request

function Get-CIPPOneDriveList {
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory = $true)]
        [string]$CustomerTenantID,
        [Parameter(Mandatory = $false)]
        [switch]$urlonly,
        [Parameter(Mandatory = $false)]
        [string]$UserUPN
    )

    Write-Verbose "Getting sites for $CustomerTenantID"
    $endpoint = "/api/listsites"
    $params = @{
        tenantfilter = $CustomerTenantID
        type = "OneDriveUsageAccount"
        userupn = $UserUPN
    }

    if ($urlonly) {
        $params.URLOnly = "true"
    }

    Invoke-CIPPRestMethod -Endpoint $endpoint -Params $params
}

**Comment by BNWEIN** [comment]
Hey! Thanks for the FR. I am away at the moment enjoying sangria on the beach! But as soon as I get back in September I'll get this added

**Comment by BNWEIN** [comment]
This has just been added to dev, and will be in the next release. 

Get-CIPPOneDriveList -CustomerTenantID 7204690c-50f4-40ee-961d-9423957a8a05

or

Get-CIPPOneDriveList -CustomerTenantID 7204690c-50f4-40ee-961d-9423957a8a05 -UserUPN User@domain.com
