### ISSUE TITLE
[Feature Request]: "Name" parameter for New-CIPPUserOffboarding

### ISSUE THREAD

**Issue by idtcipp** [BNWEIN/CIPPAPIModule#23]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Firstly, thank you for this module. It makes life a lot easier for an API Lahmen like me!

Can I request that the "Name" parameter be added to the New-CIPPUserOffboarding function? It would be useful to pass in a ticket ID in conjunction with an email post-execution, and would mean any results could automatically land in the correct ticket in our [Halo] PSA. 

Thanks. :)

**Comment by BNWEIN** [comment]
HI

Unfortunately that "Name" is hard coded on CIPP's side in the "Invoke-CIPPOffboardingJob" command. Its not a parameter we can supply. You would have to raise a feature request on CIPP to ask them to allow that name to be supplied as part of the request body. 

I am going to go ahead and close this as there is not anything i can change on the module to fix this. 

Sorry!
